### ISSUE TITLE
Immutable state

### ISSUE THREAD

**Issue by hatemhosny** [UltimateAngular/redux-store#8]
First, I want to thank you very much. I learnt a lot!

I have a comment:
I think getting the value of the state like that still exposes it to mutation (because objects are assigned by reference)
https://github.com/UltimateAngular/redux-store/blob/9109ef8fd4b0639008975682fc4e7be33b275a1f/src/store/store.ts#L13

consider if I add this to `button.addEventListener`
``` js
    let state = store.value;
    state.todos = { mutated: true };
    console.log('Original state:::', store.value);
    console.log('Mutated state:::', state);
```

I think it is better to do this
``` js
  get value() {
    return { ...this.state };
  }
```

please correct me if I'm wrong. I'm still learning :)

thanks 👍

**Comment by toddmotto** [comment]
Glad to hear! That’s correct you can definitely mutate the values - this is mostly for learning rather than a production ready store, however you can add an Object.freeze() as well to get that immutability :)! Using the spread would return a new state per property access so you’d be mutating different values. Great question!
